### PR TITLE
fix(): tutorial_issues

### PR DESCRIPTION
**Pull request by gilgda**
Fixed all issues with the typo and punctuation

### CODE REVIEW

**Comment by DevVersion** [comment]
AWESOME! :+1:

**Comment by Lordnoname** [comment]
@gilgda @DevVersion Please reference all issues you worked on this commit, using Reference #25!

**Comment by DevVersion** [comment]
@Lordnoname When a PR is already merged... you should not reference commits through GitHub messages. As I said these should be referenced at commit message time. Amending the commit is only a quick-fix. I wan't my collaborators to reference the depending issues at commit time. 

Latest example @Lordnoname 



So please don't amend commits and even with wrong references. 
Or just with writing `References #25` under a PR isn't good enough.

Something else @Lordnoname:
- **DONT** force push to master.... that's why you should amend commits locally and then push through a normal `git push`. This will prevent conflicts in the repository.

**Comment by Lordnoname** [comment]
@gilgda @DevVersion Is the branch fix/tutorialissues still needed?

**Comment by DevVersion** [comment]
Not anymore

**Pull request closed without merging**
