### PR TITLE
feat():add javatutorial

### PR DESCRIPTION
**Pull request by gilgda**
Added a link to a website which displays the java- basics

### CODE REVIEW

**Comment by Lordnoname** [comment]
@gilgda Is that link clickable?

**Comment by DevVersion** [comment]
To be honest, I don't like that, it's just a link to an external site, it would look really weird on the distributed page.

**Comment by gilgda** [comment]
Talked about the tutorial with @IngolfSchmitt a few days ago, agreed on an external tutorial because a selfwritten one would be unnecessary when there already very good ones

**Comment by DevVersion** [comment]
I'm just curious what the actual user thinks about that.. the guides should just show things that relate to our school computers.

cc. @IngolfSchmitt

**Comment by IngolfSchmitt** [comment]
I think you`re both right. The main relation of our tutorial is to our school computers and the work done on our school computers. So in the tutorial should be topics to our school. But why not giving further links to good pages showing how to use our programs ?

**Comment by DevVersion** [comment]
@IngolfSchmitt That may require another section. I won't register this as a own tutorial, it rather requires a URL collection.

**Comment by IngolfSchmitt** [comment]
Maybe a good idea.

**Comment by gilgda** [comment]
Totally agree with that :sweat_smile:

**Comment by gilgda** [comment]
Any suggestions how to go on? Maybe just await the BlueJ tutorial?

**Comment by DevVersion** [comment]
@gilgda I agree, I will close that PR since it is actually rejected. Thanks for the effort!

**Pull request closed without merging**
