### PR TITLE
feat(): add dependency badge

### PR DESCRIPTION
**Pull request by Lordnoname**
add dependency badge

### CODE REVIEW

**Comment by moritzkoenig** [comment]
Looks good to me

**Comment by Lordnoname** [comment]
@moritzkoenig Stop pressing the green merge button like @DevVersion! Merge it manually per Command-Line

**Comment by DevVersion** [comment]
@Lordnoname Indeed!, @Lordnoname stop modifying images using Photoshop :smiley:

**Comment by Lordnoname** [comment]
I didn't photoshop this picture :octopus: Look at #4

**Comment by DevVersion** [comment]
@Lordnoname That means not, that the `GREEN BUTTON` was pressed. This was just a normal CLI Merge for multiple commits using `git merge [BRANCH]` :+1:

**Pull request merged**
