### PR TITLE
fix(): typo

### PR DESCRIPTION
**Pull request by gilgda**
Fixed a formal mistake.

### CODE REVIEW

**Comment by Lordnoname** [comment]
LGTM

**Comment by Lordnoname** [comment]
...besides please write 'ihrem in pre-upper case'

**Comment by DevVersion** [comment]
@Lordnoname As the main PR reviewer, I give you the permission to merge pull requests into master, but the PR must be reviewed by two persons.

**Comment by DevVersion** [comment]
LGTM

**Comment by gilgda** [comment]
Squashed like a pro... :laughing:

**Comment by DevVersion** [comment]
@Lordnoname You should apply the close references, to show that the actual commit is related to this PR.

**Comment by Lordnoname** [comment]
@DevVersion Sorry, i forgot that.

**Comment by DevVersion** [comment]
Then you should amend the commit?

**Pull request closed without merging**
